cmake: Add C library dependency to ot-config target
Apparently linking `-lc` within `zephyr_link_library` did not ensure
that C library is linked after OpenThread libs, which in result could
lead to linker errors (for instance "undefined reference to
`isupper'").

Fix this by using `target_link_libraries` command on the ot-config
target instead, which is linked with every OT library generated.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>